version: '3'

services:

  php:
    build:
      context: .
      dockerfile: ./docker-compose/php_config
    container_name: php
    restart: unless-stopped
    volumes:
      - ./${SRC_FOLDER}:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./${SRC_FOLDER}:/var/www/html
      - ./docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

